export const loanProducts = [
  {
    id: "hdfc-instant-loan",
    name: "HDFC Instant Loan",
    description: "Hassle-free and Pre-approved Loan offered to HDFC Bank Credit Cardholders",
    amount: "Up to ₹15 Lakhs",
    rate: "10.88%",
    tenure: "6 to 48 months",
    features: ["Instant Disbursal", "100% Digital Journey", "Pre-approved for cardholders"],
    eligibility: ["HDFC Bank Credit Card required"],
    documents: ["No Documents required"],
    affiliateLink: "https://bitli.in/1PSoadc",
    category: "Instant Loan",
  },
  {
    id: "poonawalla-fincorp",
    name: "Poonawalla Fincorp Personal Loan",
    description: "Experience a seamless 100% digital process with instant approval",
    amount: "Up to ₹15,00,000",
    rate: "11.50%",
    tenure: "6 to 84 months",
    features: ["Instant Approval", "Minimal Documentation", "Zero Foreclosure Charges"],
    eligibility: ["Age: 25-55 years", "Min Income: ₹3,00,000 p.a.", "Credit Score: 720+"],
    documents: ["PAN Card"],
    affiliateLink: "https://bitli.in/eQRI1PT",
    category: "Personal Loan",
  },
  {
    id: "myeazyloan",
    name: "MyEazyLoan - Personal Loan Platform",
    description: "Compare loan offers instantly from verified lenders",
    amount: "Up to ₹50,00,000",
    rate: "As per lender",
    tenure: "6 to 84 months",
    features: ["Compare Multiple Lenders", "Transparent Terms", "Fast & Secure"],
    eligibility: ["Age: 18-60 years", "Credit Score: 700+"],
    documents: ["PAN Card", "Aadhaar", "Bank Statements"],
    affiliateLink: "https://bitli.in/p049yTd",
    category: "Loan Aggregator",
  },
  {
    id: "hero-fincorp",
    name: "Hero Fincorp Personal Loan",
    description: "Diversified Financial services provider with 100% digital journey",
    amount: "Up to ₹5 Lakhs",
    rate: "19% to 26%",
    tenure: "Up to 36 months",
    features: ["100% Digital Journey", "No Paperwork", "Quick Disbursal"],
    eligibility: ["Age: 21-45 years", "Income: ₹20,000/monthly", "CIBIL: 750+"],
    documents: ["PAN Card", "Aadhaar Card"],
    affiliateLink: "https://bitli.in/uSoN3mg",
    category: "Quick Loan",
  },
  {
    id: "zype",
    name: "Zype Personal Loan",
    description: "Get instant line of credit with zero foreclosure fees",
    amount: "₹5,000 to ₹1,50,000",
    rate: "Market competitive",
    tenure: "6 to 12 months",
    features: ["60 Second Approval", "Zero Foreclosure Fees", "Flexible Tenure"],
    eligibility: ["Age: 21-50 years", "Salaried Income: ₹20,000/monthly", "Credit Score: 650+"],
    documents: ["No Documents required"],
    affiliateLink: "https://bitli.in/P3iBrci",
    category: "Instant Credit",
  },
  {
    id: "cashe",
    name: "CASHe Personal Loan",
    description: "Instant Personal Loans for young salaried professionals",
    amount: "Up to ₹3 Lakhs",
    rate: "From 25%",
    tenure: "Up to 18 months",
    features: ["Zero Foreclosure Charges", "100% Digital Journey", "Quick Approval"],
    eligibility: ["Age: 23-55 years", "Salaried Income: ₹50,000/monthly", "Credit Score: 650+"],
    documents: ["PAN Card", "3 months Banking"],
    affiliateLink: "https://bitli.in/p7XtsyR",
    category: "Quick Loan",
  },
  {
    id: "bajaj-finserv",
    name: "Bajaj Finserv Personal Loan",
    description: "Manage a wide range of expenses with flexible repayment",
    amount: "Up to ₹55 Lakhs",
    rate: "From 11%",
    tenure: "Up to 96 months",
    features: ["High Loan Amount", "Flexible Tenure", "Overdraft Services", "Quick Approval"],
    eligibility: ["Age: 25-57 years", "Salaried Income: ₹35,000/monthly", "Credit Score: 685+"],
    documents: ["PAN Card", "Aadhaar", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/l2EMs89",
    category: "Personal Loan",
  },
  {
    id: "axis-bank",
    name: "Axis Bank Personal Loan",
    description: "Quick Personal Loans with balance transfer services",
    amount: "Up to ₹40 Lakhs",
    rate: "From 9.99%",
    tenure: "Up to 84 months",
    features: ["Lowest Interest Rates", "Balance Transfer", "Quick Disbursal", "Minimal Paperwork"],
    eligibility: ["Age: 21-60 years", "Salaried Income: ₹30,000-40,000/monthly", "Credit Score: 700+"],
    documents: ["PAN Card", "Aadhaar", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/WYqqsOe",
    category: "Personal Loan",
  },
  {
    id: "tata-capital",
    name: "Tata Capital Personal Loan",
    description: "Meet your urgent financial needs with flexible options",
    amount: "Up to ₹50 Lakhs",
    rate: "Competitive rates",
    tenure: "Up to 72 months",
    features: ["High Loan Amount", "Balance Transfer", "Overdraft Services", "Quick Approval"],
    eligibility: ["Age: 21-58 years", "Salaried Income: ₹25,000/monthly", "Credit Score: 725+"],
    documents: ["PAN Card", "Aadhaar", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/9nsAciY",
    category: "Personal Loan",
  },
  {
    id: "hsbc",
    name: "HSBC Personal Loan",
    description: "Hassle-free financing with attractive interest rates",
    amount: "Up to ₹50 Lakhs",
    rate: "From 9.99%",
    tenure: "Up to 60 months",
    features: ["Instant Disbursal", "100% Digital Journey", "Quick Approval", "No Paperwork"],
    eligibility: [
      "Existing HSBC Customer",
      "Age: 21-58 years",
      "Salaried Income: ₹35,000/monthly",
      "Credit Score: 730+",
    ],
    documents: ["PAN Card", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/bcNFe8m",
    category: "Personal Loan",
  },
  {
    id: "hdfc-bank",
    name: "HDFC Bank Personal Loan",
    description: "Quick disbursals with flexible repayment options",
    amount: "Up to ₹75 Lakhs",
    rate: "From 10.80%",
    tenure: "Up to 84 months",
    features: ["Lowest Interest Rates", "Quick Approval", "Flexible Tenure", "Hassle-free Process"],
    eligibility: ["Age: 21-60 years", "Salaried Income: ₹30,000-50,000/monthly", "Credit Score: 700+"],
    documents: ["PAN Card", "Aadhaar", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/pZ7dlYe",
    category: "Personal Loan",
  },
  {
    id: "kotak811",
    name: "Kotak811 Bank Savings Account",
    description: "Earn Interest as you Save Money with zero balance",
    amount: "Min ₹1,000",
    rate: "3.25% p.a.",
    tenure: "N/A",
    features: ["No Minimum Balance", "100% Digital", "High Interest Rate", "All Banking Services"],
    eligibility: ["Age: 18-60 years"],
    documents: ["PAN Card", "Aadhaar Card"],
    affiliateLink: "https://bitli.in/BJuCnZ7",
    category: "Savings Account",
  },
  {
    id: "olyv",
    name: "Olyv Personal Loan",
    description: "India's trusted digital lending platform",
    amount: "Up to ₹2 Lakhs",
    rate: "Competitive rates",
    tenure: "Flexible tenure",
    features: ["100% Digital Journey", "Quick Approval", "Quick Disbursal", "Minimal Paperwork"],
    eligibility: ["Age: 21-45 years", "Income: ₹20,000/monthly", "Credit Score: 680+"],
    documents: ["PAN Card", "Aadhaar", "Bank statements & Pay Slips"],
    affiliateLink: "https://bitli.in/olY0Egq",
    category: "Personal Loan",
  },
  {
    id: "mpokket",
    name: "mPokket Instant Loan App",
    description: "Instant Loan App for quick financial solutions",
    amount: "Up to ₹50,000",
    rate: "Market competitive",
    tenure: "Flexible",
    features: ["100% Digital Journey", "Low CIBIL Accepted", "New to Credit OK", "Student Friendly"],
    eligibility: ["Age: 18-45 years", "Students & Salaried", "Min Salary: ₹9,000/monthly"],
    documents: ["PAN Card", "Aadhaar", "College ID for Students"],
    affiliateLink: "https://bitli.in/BFDStgz",
    category: "Quick Loan",
  },
  {
    id: "prefr",
    name: "Prefr Loans",
    description: "Financial independence begins with Prefr",
    amount: "Up to ₹3 Lakhs",
    rate: "Competitive rates",
    tenure: "Flexible",
    features: ["24X7 Access to Funds", "100% Digital", "Minimal Documentation", "For Salaried & Self-Employed"],
    eligibility: ["Age: 22-55 years", "Income: ₹25,000/monthly", "Credit Score: 725+"],
    documents: ["PAN Card", "Bank statements"],
    affiliateLink: "https://bitli.in/4dXe3j6",
    category: "Personal Loan",
  },
]

export const creditCardProducts = [
  {
    id: "axis-myzone",
    name: "Axis MyZone Visa Credit Card",
    description: "Entry level card offering benefits across Shopping, Dining and Entertainment",
    type: "Lifestyle Card",
    fees: "Lifetime FREE",
    benefits: ["Buy 1 Get 1 Movie Tickets", "₹2,880 annual Swiggy savings", "Lounge access", "SonyLiv Premium"],
    cashback: "4 Edge points per ₹200",
    eligibility: ["Age: 21-65 years", "Income: ₹25,000+ monthly", "Credit Score: 735+"],
    affiliateLink: "https://bitli.in/F129erC",
    category: "Lifestyle",
  },
  {
    id: "axis-flipkart",
    name: "Axis Flipkart Credit Card",
    description: "Best Credit Card for Flipkart Shopping with accelerated cashback",
    type: "Shopping Card",
    fees: "₹500 (waived on ₹3.5L+ spend)",
    benefits: ["7.5% Flipkart Myntra", "5% Cleartrip", "4% Swiggy/Uber", "₹250 welcome voucher"],
    cashback: "Up to 7.5%",
    eligibility: ["Age: 21-65 years", "Income: ₹25,000+ monthly", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/bjbj87N",
    category: "Shopping",
  },
  {
    id: "sbi-cashback",
    name: "SBI Cashback Credit Card",
    description: "India's best cashback card for online spends",
    type: "Cashback Card",
    fees: "₹999 (waived on ₹2L+ spend)",
    benefits: ["5% online cashback", "1% offline cashback", "Fuel surcharge waiver", "Auto-credited cashback"],
    cashback: "Up to 5%",
    eligibility: ["Age: 21-65 years", "Income: ₹30,000+ monthly", "Credit Score: 650+"],
    affiliateLink: "https://bitli.in/H1FTrl7",
    category: "Cashback",
  },
  {
    id: "indusind-tiger",
    name: "Indusind Tiger Credit Card",
    description: "LIFETIME FREE with no joining or annual fees",
    type: "Basic Card",
    fees: "Lifetime FREE",
    benefits: ["No annual charges", "Basic rewards", "Easy approval"],
    cashback: "Rewards on spends",
    eligibility: ["Basic eligibility", "Good income"],
    affiliateLink: "https://bitli.in/N7VA661",
    category: "Basic",
  },
  {
    id: "sbi-simply-click",
    name: "SBI Simply Click Credit Card",
    description: "Entry level credit card designed for internet purchases",
    type: "Online Shopping Card",
    fees: "Zero annual fees",
    benefits: ["5% cashback on online", "1% on other spends", "Easy approval"],
    cashback: "Up to 5%",
    eligibility: ["Good online shopping history"],
    affiliateLink: "https://bitli.in/MTz5aI0",
    category: "Online",
  },
  {
    id: "axis-privilege",
    name: "Axis Privilege Credit Card",
    description: "Premium card with exclusive shopping and travel benefits",
    type: "Premium Card",
    fees: "₹1,500 annual",
    benefits: ["12,500 reward points", "8 lounge accesses yearly", "15% flight discounts", "25% dining discounts"],
    cashback: "Up to 12,500 points",
    eligibility: ["Age: 21-65 years", "Income: ₹50,000+ monthly", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/AJ5ypdc",
    category: "Premium",
  },
  {
    id: "axis-magnus",
    name: "Axis Magnus Credit Card",
    description: "Premium card for heavy spenders with unlimited international lounges",
    type: "Luxury Card",
    fees: "₹12,500 (waived on ₹25L+ spend)",
    benefits: ["1.2% back up to ₹1.5L", "3.5% above ₹1.5L", "Unlimited int'l lounges", "₹12,500 welcome voucher"],
    cashback: "Up to 3.5%",
    eligibility: ["Age: 21-65 years", "Income: ₹1,50,000+ monthly", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/AYMCsUo",
    category: "Luxury",
  },
  {
    id: "axis-iocl",
    name: "Axis IOCL Rupay Credit Card",
    description: "Simple fuel card that pays for your drive",
    type: "Fuel Card",
    fees: "₹500 (waived on ₹3.5L+ spend)",
    benefits: ["4% IOCL fuel", "1% surcharge waiver", "1% online", "15% dining discounts"],
    cashback: "Up to 4%",
    eligibility: ["Age: 21-65 years", "Income: ₹25,000+ monthly", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/jk4HHOI",
    category: "Fuel",
  },
  {
    id: "axis-airtel",
    name: "Axis Airtel Credit Card",
    description: "Best Card for Airtel Users with utility bill discounts",
    type: "Utility Card",
    fees: "₹500 (waived on ₹2L+ spend)",
    benefits: ["25% Airtel cashback", "10% utilities", "10% Swiggy/Zomato", "4 lounge visits"],
    cashback: "Up to 25%",
    eligibility: ["Age: 21-65 years", "Income: ₹25,000+ monthly", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/bMU3oIK",
    category: "Utility",
  },
  {
    id: "axis-lic-signature",
    name: "Axis LIC Signature Credit Card",
    description: "Paying LIC Premiums gets better with this card",
    type: "LIC Card",
    fees: "Lifetime FREE",
    benefits: ["0.4% LIC premium", "0.4% abroad", "0.2% other", "1% fuel waiver"],
    cashback: "0.4% on LIC",
    eligibility: ["Age: 21-65 years", "Annual Income: ₹5L+", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/7YMNUq9",
    category: "Specialized",
  },
  {
    id: "axis-lic-platinum",
    name: "Axis LIC Platinum Credit Card",
    description: "Enjoy dining discounts and card protection",
    type: "LIC Card",
    fees: "Lifetime FREE",
    benefits: ["0.4% LIC premium", "0.4% abroad", "0.2% other", "15% dining"],
    cashback: "0.4% on LIC",
    eligibility: ["Age: 21-65 years", "Annual Income: ₹3L+", "Credit Score: 736+"],
    affiliateLink: "https://bitli.in/oQjbvfK",
    category: "Specialized",
  },
  {
    id: "idfc-first-power",
    name: "IDFC First Power Rupay Credit Card",
    description: "Accelerated rewards on fuel purchases, dining, and more",
    type: "Fuel Card",
    fees: "₹199 (waived on ₹50K+ spend)",
    benefits: ["3.5% fuel savings", "Rs 250 first purchase", "Roadside assistance", "Personal accident cover"],
    cashback: "Up to 3.5%",
    eligibility: ["Age: 21-60 years", "Income: ₹25,000+ monthly"],
    affiliateLink: "https://bitli.in/Wnh6FzN",
    category: "Fuel",
  },
  {
    id: "idfc-first-power-plus",
    name: "IDFC First Power Plus Credit Card",
    description: "Enhanced fuel rewards up to 6.5%",
    type: "Fuel Card",
    fees: "₹499 (waived on ₹150K+ spend)",
    benefits: ["5% fuel savings", "Rs 500 first purchase", "Roadside assistance", "Personal accident cover"],
    cashback: "Up to 6.5%",
    eligibility: ["Age: 21-60 years", "Income: ₹25,000+ monthly"],
    affiliateLink: "https://bitli.in/LusYwKn",
    category: "Fuel",
  },
  {
    id: "idfc-first",
    name: "IDFC First Credit Card",
    description: "Lifetime free credit card with never expiring rewards",
    type: "Cashback Card",
    fees: "Lifetime FREE",
    benefits: ["Never expiring rewards", "Railway lounge", "₹500 welcome voucher", "5% first EMI cashback"],
    cashback: "Never expires",
    eligibility: ["Age: 21-65 years", "Income: ₹25,000+ monthly", "Credit Score: 710+"],
    affiliateLink: "https://bitli.in/Jj79KD4",
    category: "Rewards",
  },
  {
    id: "idfc-swyp",
    name: "IDFC SWYP Credit Card",
    description: "Discount coupons from MakeMyTrip, EaseMyTrip & More",
    type: "Travel Card",
    fees: "Joining fee varies",
    benefits: ["₹2,100 EaseMyTrip coupons", "Lenskart membership", "Travel discounts", "Shopping offers"],
    cashback: "Varies by category",
    eligibility: ["As per IDFC terms"],
    affiliateLink: "https://bitli.in/Smpj4Sz",
    category: "Travel",
  },
]
