import type { Metadata } from "next"
import Link from "next/link"
import { createClient } from "@/lib/supabase/server"
import { formatINR, shopItems } from "@/lib/shop-data"

export const metadata: Metadata = { title: "Price intelligence | ShopNdeal", description: "Review verified ShopNdeal price observations without invented history." }

export default async function PriceIntelligencePage() {
  const supabase = await createClient()
  const { data: observations } = await supabase.from("shop_price_observations").select("product_slug, price, availability, source, observed_at").eq("is_valid", true).order("observed_at", { ascending: false }).limit(100)
  const rows = observations ?? []
  const byProduct = shopItems.map((item) => ({ item, observations: rows.filter((observation) => observation.product_slug === item.slug) })).filter((row) => row.observations.length)
  return <main className="min-h-screen bg-[#f7f9fc] px-6 py-12 text-slate-950"><div className="mx-auto max-w-6xl"><Link href="/shop" className="text-sm font-bold text-blue-700">← Back to ShopNdeal</Link><p className="mt-10 text-sm font-black uppercase tracking-[0.2em] text-blue-600">Verified data</p><h1 className="mt-3 text-4xl font-black tracking-tight">Price intelligence</h1><p className="mt-3 max-w-2xl text-slate-600">A factual view of authorized price observations. Products without enough verified history are intentionally omitted rather than filled with estimates.</p>{byProduct.length ? <div className="mt-10 grid gap-5 md:grid-cols-2">{byProduct.map(({ item, observations: productObservations }) => { const latest = productObservations[0]; const lowest = Math.min(...productObservations.map((observation) => Number(observation.price))); return <Link key={item.slug} href={`/shop/product/${item.slug}`} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p className="text-xs font-black uppercase tracking-[0.14em] text-slate-400">{item.merchant} · {productObservations.length} observations</p><h2 className="mt-2 text-xl font-black">{item.name}</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Latest</p><p className="mt-1 text-xl font-black">{formatINR(Number(latest.price))}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Lowest observed</p><p className="mt-1 text-xl font-black">{formatINR(lowest)}</p></div></div><p className="mt-4 text-xs font-bold capitalize text-slate-400">{latest.availability.replaceAll("_", " ")} · {latest.source.replaceAll("_", " ")}</p></Link> })}</div> : <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-8"><h2 className="text-xl font-black">Verified history is not available yet</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">ShopNdeal will show price history when authorized merchant, affiliate, or approved import observations are available.</p></section>}<p className="mt-8 text-xs leading-5 text-slate-400">Prices and availability can change at the merchant. This page does not make price guarantees.</p></div></main>
}
