import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, Banknote, BusFront, Check, CircleDollarSign, CreditCard, Handshake, MapPin, Menu, Network, Orbit, QrCode, ShieldCheck, Smartphone, Sparkles, TrainFront, Trophy, WalletCards, Zap } from "lucide-react"
import { GoContactForm } from "@/components/go-contact-form"

export const metadata: Metadata = { title: "BuyNswipe® Go | Tap. Travel. Earn.", description: "A mobility-led payments and rewards platform built around NCMC-enabled travel." }

const nav = ["About", "Credit", "Payment Solutions", "BuyNswipe® Go", "Solutions", "Resources", "Blog"]
const pillars = [
  { icon: TrainFront, title: "NCMC ready", text: "Designed for modern, connected mobility experiences." },
  { icon: WalletCards, title: "One digital experience", text: "Bring journeys, payments and rewards into one place." },
  { icon: Trophy, title: "Rewards ecosystem", text: "Create meaningful engagement beyond the commute." },
]
const audiences = [
  ["Transit operators", "Simplify rider experiences and unlock new engagement layers.", TrainFront],
  ["Banks & issuers", "Build relevant card propositions around everyday movement.", Banknote],
  ["Payment partners", "Connect acceptance, settlement and customer value.", CreditCard],
  ["Merchants", "Reach commuters with contextual offers and rewards.", QrCode],
]

function Logo() { return <Link href="/" className="flex items-center gap-2" aria-label="BuyNswipe® home"><span className="flex size-9 items-center justify-center rounded-xl bg-go-blue text-lg font-black text-primary-foreground">B</span><span className="text-lg font-extrabold tracking-tight text-go-navy">BuyNswipe<sup>®</sup></span></Link> }
function CardMockup() { return <div className="relative mx-auto flex min-h-[430px] w-full max-w-[560px] items-center justify-center overflow-hidden rounded-[2rem] bg-go-navy p-8 shadow-2xl shadow-go-blue/20"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(35deg,transparent_35%,#008CFF_36%,transparent_37%),linear-gradient(145deg,transparent_52%,#39D353_53%,transparent_54%)] [background-size:90px_90px,130px_130px]" /><div className="absolute -right-16 top-14 size-56 rounded-full border border-go-cyan/40" /><div className="absolute -right-8 top-28 size-40 rounded-full border border-go-cyan/30" /><div className="relative w-full max-w-[410px] rotate-[-8deg] rounded-3xl border border-primary-foreground/25 bg-gradient-to-br from-go-navy via-go-blue to-go-cyan p-6 text-primary-foreground shadow-2xl transition-transform duration-500 hover:rotate-0"><div className="flex items-start justify-between"><span className="text-sm font-semibold tracking-[0.18em]">BuyNswipe<sup>®</sup></span><span className="text-xs font-bold tracking-widest text-go-lime">GO</span></div><div className="flex h-40 items-center justify-center"><span className="text-[9rem] font-black leading-none text-primary-foreground/90">G</span></div><div className="flex items-end justify-between"><div><div className="mb-1 text-[10px] uppercase tracking-widest text-primary-foreground/60">Mobility companion</div><div className="text-sm font-semibold">TAP. TRAVEL. EARN.</div></div><WifiMark /></div></div><div className="absolute bottom-8 left-8 rounded-full bg-go-lime px-4 py-2 text-xs font-black tracking-widest text-go-navy">NCMC ENABLED</div></div> }
function WifiMark() { return <span className="text-2xl" aria-hidden="true">)))</span> }

export default function GoPage() { return <main className="min-h-screen bg-go-bg text-go-navy">
  <header className="sticky top-0 z-50 border-b border-go-navy/10 bg-go-bg/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8"><Logo /><nav className="hidden items-center gap-5 xl:flex">{nav.map((item) => <Link key={item} href={item === "BuyNswipe® Go" ? "/go" : `/#${item.toLowerCase().replaceAll(" ", "-")}`} className={item === "BuyNswipe® Go" ? "font-bold text-go-blue" : "text-sm font-medium text-go-navy/70 hover:text-go-blue"}>{item}</Link>)}</nav><div className="flex items-center gap-3"><Link href="#partner" className="hidden rounded-full bg-go-navy px-5 py-2.5 text-sm font-bold text-primary-foreground transition hover:bg-go-blue sm:inline-flex">Partner With Us</Link><button className="rounded-xl border border-go-navy/15 p-2 xl:hidden" aria-label="Open navigation"><Menu className="size-5" /></button></div></div></header>
  <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1fr_1fr] lg:px-8 lg:pb-28 lg:pt-24"><div><span className="go-kicker"><Orbit className="size-4" /> NCMC-enabled mobility platform</span><h1 className="mt-6 max-w-2xl text-balance text-5xl font-black leading-[1.02] tracking-[-0.05em] sm:text-7xl">Move smarter with <span className="go-gradient-text">BuyNswipe<sup>®</sup> Go.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-go-navy/70">One mobility card and digital experience for transit, payments, rewards and everyday journeys.</p><p className="mt-4 max-w-xl leading-7 text-go-navy/60">Built to connect mobility with payments and customer engagement — giving commuters, merchants, transit operators and partners a smarter way to move and transact.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#partner" className="inline-flex items-center gap-2 rounded-full bg-go-blue px-6 py-3.5 font-bold text-primary-foreground transition hover:bg-go-navy">Get BuyNswipe® Go <ArrowRight className="size-4" /></Link><Link href="#partner" className="inline-flex items-center rounded-full border border-go-navy/20 px-6 py-3.5 font-bold transition hover:border-go-blue hover:text-go-blue">Partner With Us</Link></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-go-navy/50">NCMC · Transit · Payments · Rewards · Merchant acceptance</p></div><div><CardMockup /><p className="mt-5 text-center text-sm font-black uppercase tracking-[0.3em] text-go-blue">Tap. Travel. Earn.</p></div></section>
  <section className="border-y border-go-navy/10 bg-primary-foreground"><div className="mx-auto grid max-w-7xl gap-px bg-go-navy/10 sm:grid-cols-2 lg:grid-cols-5">{[ [ShieldCheck,"NCMC Ready"],[TrainFront,"Transit Focused"],[Smartphone,"Digital Experience"],[Trophy,"Rewards Ecosystem"],[Handshake,"Partner Powered"]].map(([Icon,label]) => <div key={label as string} className="flex items-center gap-3 bg-primary-foreground px-5 py-5 text-sm font-bold"><Icon className="size-5 text-go-blue" />{label as string}</div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><span className="go-kicker">The everyday mobility layer</span><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">More than a card. A connected journey.</h2></div><p className="max-w-xl text-lg leading-8 text-go-navy/65">BuyNswipe® Go brings together the moments around movement — from tapping into transit to discovering rewards at the places you already visit.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{pillars.map(({icon: Icon,title,text}) => <article key={title} className="rounded-3xl border border-go-navy/10 bg-primary-foreground p-7 shadow-sm"><div className="mb-14 flex size-12 items-center justify-center rounded-2xl bg-go-blue/10 text-go-blue"><Icon className="size-6" /></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-go-navy/60">{text}</p></article>)}</div></section>
  <section className="bg-go-navy px-5 py-24 text-primary-foreground lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><span className="go-kicker go-kicker-dark">Built for the whole ecosystem</span><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">One platform. Many ways to move forward.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{audiences.map(([title,text,Icon]) => <article key={title as string} className="rounded-3xl border border-primary-foreground/15 bg-primary-foreground/5 p-6"><Icon className="size-7 text-go-lime" /><h3 className="mt-14 text-lg font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/65">{text as string}</p><ArrowRight className="mt-7 size-5 text-go-cyan" /></article>)}</div></div></section>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><div><span className="go-kicker">The product ecosystem</span><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Designed around real-world journeys.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-go-navy/65">A flexible foundation for transit access, digital payments, loyalty and partner-led experiences — built to grow as your network grows.</p><ul className="mt-8 flex flex-col gap-4">{["Transit and mobility access", "Digital card and payment experiences", "Partner offers and rewards", "Data-led customer engagement"].map((item) => <li key={item} className="flex items-center gap-3 font-semibold"><span className="flex size-6 items-center justify-center rounded-full bg-go-green/15 text-go-green"><Check className="size-4" /></span>{item}</li>)}</ul></div><div className="rounded-[2rem] bg-gradient-to-br from-go-blue to-go-green p-px"><div className="rounded-[2rem] bg-go-bg p-8"><div className="flex items-center justify-between border-b border-go-navy/10 pb-5"><span className="font-bold">Your journey, connected</span><Zap className="size-5 text-go-blue" /></div><div className="flex flex-col gap-5 py-7"><div className="flex items-center gap-4"><span className="flex size-11 items-center justify-center rounded-2xl bg-go-blue text-primary-foreground"><TrainFront className="size-5" /></span><div><p className="font-bold">Metro ride</p><p className="text-sm text-go-navy/55">Tap in · 09:42 AM</p></div><span className="ml-auto text-sm font-bold text-go-green">+10 points</span></div><div className="ml-5 h-8 border-l-2 border-dashed border-go-blue/30" /><div className="flex items-center gap-4"><span className="flex size-11 items-center justify-center rounded-2xl bg-go-lime text-go-navy"><CircleDollarSign className="size-5" /></span><div><p className="font-bold">Cafe reward</p><p className="text-sm text-go-navy/55">Partner offer unlocked</p></div><span className="ml-auto text-sm font-bold text-go-blue">Redeem</span></div></div></div></div></section>
  <section id="partner" className="bg-go-blue px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="text-primary-foreground"><Sparkles className="size-8 text-go-lime" /><h2 className="mt-6 text-4xl font-black tracking-tight sm:text-5xl">Let&apos;s build the next journey.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-primary-foreground/75">Whether you operate a network, issue cards, power payments or build experiences, there is a place for you in the BuyNswipe® Go ecosystem.</p><div className="mt-8 flex flex-wrap gap-3 text-sm font-semibold"><span className="rounded-full bg-primary-foreground/10 px-4 py-2">Enterprise ready</span><span className="rounded-full bg-primary-foreground/10 px-4 py-2">Partner led</span><span className="rounded-full bg-primary-foreground/10 px-4 py-2">Mobility first</span></div></div><div className="rounded-3xl bg-primary-foreground p-6 sm:p-8"><GoContactForm /></div></div></section>
  <footer className="bg-go-navy px-5 py-8 text-primary-foreground/60 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-xs leading-6 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} BuyNswipe Technology Pvt. Ltd. All rights reserved.</span><span>BuyNswipe® Go is a proposed mobility and payments platform. Availability and features may vary by partner, city and applicable regulations.</span></div></footer>
</main> }
