import type { Metadata } from "next"
import Link from "next/link"
import { createClient } from "@/lib/supabase/server"

export const metadata: Metadata = { title: "My ShopNdeal cashback | BuyNswipe", description: "Review provider-confirmed ShopNdeal cashback activity and statuses." }

const statusStyles: Record<string, string> = { pending: "bg-amber-50 text-amber-700", confirmed: "bg-cyan-50 text-cyan-700", paid: "bg-emerald-50 text-emerald-700", returned: "bg-rose-50 text-rose-700", cancelled: "bg-slate-100 text-slate-600", rejected: "bg-rose-50 text-rose-700" }

export default async function ShopCashbackPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return <main className="mx-auto max-w-3xl px-6 py-20"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">ShopNdeal</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950">Your cashback, clearly tracked.</h1><p className="mt-4 text-slate-600">Sign in to view cashback records confirmed by connected shopping partners.</p><Link href="/auth/login?next=/shop/cashback" className="mt-8 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">Sign in to continue</Link></main>
  const { data: cashback } = await supabase.from("shop_cashback").select("id, merchant, cashback_amount, currency, status, available_at, created_at").eq("user_id", user.id).order("created_at", { ascending: false })
  const rows = cashback ?? []
  const confirmed = rows.filter((row) => ["confirmed", "paid"].includes(row.status)).reduce((sum, row) => sum + Number(row.cashback_amount ?? 0), 0)
  return <main className="min-h-screen bg-[#f7f9fc] px-6 py-12"><div className="mx-auto max-w-5xl"><Link href="/shop" className="text-sm font-bold text-blue-700">← Back to ShopNdeal</Link><header className="mt-8 rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">My ShopNdeal</p><h1 className="mt-3 text-4xl font-black tracking-tight">Cashback activity</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Only connected-partner records appear here. Pending cashback is not guaranteed until the partner confirms the transaction.</p><div className="mt-7 inline-flex rounded-2xl bg-white/10 px-4 py-3"><span className="text-sm text-slate-300">Confirmed or paid</span><strong className="ml-3 text-lg text-emerald-300">₹{confirmed.toFixed(2)}</strong></div></header><section className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{rows.length ? rows.map((row) => <article key={row.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5 last:border-0"><div><h2 className="font-black text-slate-950">{row.merchant}</h2><p className="mt-1 text-sm text-slate-500">Recorded {new Date(row.created_at).toLocaleDateString("en-IN")}</p></div><div className="text-right"><p className="font-black text-slate-950">{row.currency === "INR" ? "₹" : row.currency}{Number(row.cashback_amount).toFixed(2)}</p><span className={`mt-1 inline-flex rounded-full px-2.5 py-1 text-xs font-bold capitalize ${statusStyles[row.status] ?? statusStyles.pending}`}>{row.status}</span></div></article>) : <div className="p-10 text-center"><h2 className="text-xl font-black text-slate-950">No cashback activity yet</h2><p className="mt-2 text-sm text-slate-500">Shop through a connected partner route to create an attributable record.</p><Link href="/shop/products" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Browse products</Link></div>}</section></div></main>
}
