import type { Metadata } from "next"
import Link from "next/link"
import { createClient } from "@/lib/supabase/server"

export const metadata: Metadata = { title: "ShopNdeal creators | BuyNswipe", description: "Discover ShopNdeal creator campaigns and review your creator earnings." }

export default async function ShopCreatorsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: campaigns } = await supabase.from("shop_campaigns").select("id, name, slug, description, campaign_type, creator_incentive, ends_at, terms").eq("status", "approved").lte("starts_at", new Date().toISOString()).gte("ends_at", new Date().toISOString()).order("ends_at", { ascending: true })
  const profile = user ? (await supabase.from("shop_creators").select("id, display_name, status, verification_status").eq("user_id", user.id).maybeSingle()).data : null
  const earnings = profile ? (await supabase.from("shop_creator_earnings").select("amount, currency, status").eq("creator_id", profile.id)).data ?? [] : []
  const confirmed = earnings.filter((earning) => ["confirmed", "paid"].includes(earning.status)).reduce((sum, earning) => sum + Number(earning.amount ?? 0), 0)

  return <main className="min-h-screen bg-[#f7f9fc] px-6 py-12"><div className="mx-auto max-w-5xl"><Link href="/shop" className="text-sm font-bold text-blue-700">← Back to ShopNdeal</Link><header className="mt-8 rounded-3xl bg-slate-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[0.2em] text-cyan-300">ShopNdeal creators</p><h1 className="mt-3 text-4xl font-black tracking-tight">Share useful savings, transparently.</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Creator campaigns, tracked links, and earnings are separated from ordinary cashback. Earnings appear only after connected partner confirmation.</p>{profile ? <div className="mt-6 flex flex-wrap gap-3 text-xs font-bold"><span className="rounded-full bg-white/10 px-3 py-2">{profile.display_name}</span><span className="rounded-full bg-cyan-400/15 px-3 py-2 text-cyan-200">{profile.verification_status}</span><span className="rounded-full bg-emerald-400/15 px-3 py-2 text-emerald-200">Confirmed: ₹{confirmed.toFixed(2)}</span></div> : <Link href="/auth/login?next=/shop/creators" className="mt-6 inline-flex rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950">Sign in to manage creator work</Link>}</header><section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Available now</p><h2 className="mt-2 text-2xl font-black text-slate-950">Approved campaigns</h2></div><span className="text-sm text-slate-500">{campaigns?.length ?? 0} campaigns</span></div><div className="mt-4 grid gap-4 md:grid-cols-2">{campaigns?.length ? campaigns.map((campaign) => <article key={campaign.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-black text-slate-950">{campaign.name}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-400">{campaign.campaign_type.replaceAll("_", " ")}</p></div>{campaign.creator_incentive ? <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">₹{Number(campaign.creator_incentive).toFixed(0)} incentive</span> : null}</div><p className="mt-4 text-sm leading-6 text-slate-600">{campaign.description || "A verified ShopNdeal campaign with explicit partner terms."}</p><p className="mt-4 text-xs text-slate-500">Ends {new Date(campaign.ends_at).toLocaleDateString("en-IN")}</p><p className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">{campaign.terms || "Campaign terms are provided by the connected partner."}</p></article>) : <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><h3 className="font-black text-slate-950">No approved campaigns yet</h3><p className="mt-2 text-sm text-slate-500">New campaigns will appear here after partner review.</p></div>}</div></section></div></main>
}
