import Link from "next/link"
import { ArrowLeft, CheckCircle2, Clock3, ShieldCheck } from "lucide-react"
import { createClient } from "@/lib/supabase/server"
import { NewProductForm } from "./new-product-form"

export default async function AdminCreditPage() {
  const supabase = await createClient()
  const { data } = await supabase.from("credit_products").select("id,name,provider,product_type,status,source_url,review_due_at,updated_at").order("updated_at", { ascending: false })
  const products = data ?? []
  const published = products.filter((product) => product.status === "published").length
  const review = products.filter((product) => ["review", "approved"].includes(product.status)).length
  return <main className="min-h-screen bg-slate-950 text-slate-950"><div className="mx-auto min-h-screen max-w-7xl bg-slate-50 p-6 lg:p-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-sky-600"><ArrowLeft className="size-4" /> Admin overview</Link><header className="mt-8"><p className="text-sm font-semibold text-emerald-600">Product governance</p><h1 className="mt-2 text-3xl font-black">Credit catalog</h1><p className="mt-2 text-sm text-slate-500">Manage structured product facts, evidence, and publishing readiness.</p></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Published products" value={String(published)} /><Metric label="Claims in review" value={String(review)} /><Metric label="Total products" value={String(products.length)} /></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Add credit product</h2><p className="mb-4 mt-1 text-sm text-slate-500">New products start as drafts until evidence is reviewed.</p><NewProductForm /></section><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-black">Product inventory</h2></div>{products.length ? products.map((product) => <div key={product.id} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/admin/credit/${product.id}`} className="font-bold hover:text-sky-600">{product.name}</Link><p className="mt-1 text-sm text-slate-500">{product.provider} · {product.product_type}{product.source_url ? " · Evidence linked" : " · Evidence missing"}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize text-slate-600">{product.status === "published" ? <CheckCircle2 className="size-3.5 text-emerald-600" /> : product.status === "review" ? <Clock3 className="size-3.5 text-amber-600" /> : <ShieldCheck className="size-3.5" />}{product.status}</span></div>) : <p className="p-8 text-sm text-slate-500">No credit products yet.</p>}</section></div></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div> }
