import Link from "next/link"
import { ArrowLeft, BadgeIndianRupee, CheckCircle2, Clock3, ShieldCheck } from "lucide-react"

const products = [
  ["Personal loans", "12 providers", "Review due in 8 days", "review"],
  ["Credit cards", "18 providers", "All claims verified", "approved"],
  ["Business credit", "6 providers", "2 products need sources", "attention"],
]

export default function AdminCreditPage() {
  return <main className="min-h-screen bg-slate-950 text-slate-950"><div className="mx-auto min-h-screen max-w-7xl bg-slate-50 p-6 lg:p-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-sky-600"><ArrowLeft className="size-4" /> Admin overview</Link><header className="mt-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-600">Product governance</p><h1 className="mt-2 text-3xl font-black">Credit catalog</h1><p className="mt-2 text-sm text-slate-500">Review structured product facts, evidence, and publishing readiness.</p></div><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Add product</button></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Published products" value="36" /><Metric label="Claims in review" value="7" /><Metric label="Sources expiring" value="4" /></div><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-black">Product collections</h2><p className="mt-1 text-sm text-slate-500">Every rate, fee, and eligibility claim needs an evidence source and review date.</p></div>{products.map(([name, count, detail, state]) => <div key={name} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{name}</p><p className="mt-1 text-sm text-slate-500">{count} · {detail}</p></div><span className={`inline-flex w-fit items-center gap-2 rounded-full px-3 py-1 text-xs font-bold ${state === "approved" ? "bg-emerald-100 text-emerald-700" : state === "review" ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700"}`}>{state === "approved" ? <CheckCircle2 className="size-3.5" /> : state === "review" ? <Clock3 className="size-3.5" /> : <ShieldCheck className="size-3.5" />} {state}</span></div>)}</section></div></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div> }
