import { formatINR } from "@/lib/shop-data"

type PriceObservation = { price: number; original_price: number | null; currency: string; availability: string; source: string; observed_at: string }

export function ShopPriceHistory({ observations }: { observations: PriceObservation[] }) {
  if (!observations.length) return <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Price intelligence</p><h2 className="mt-2 text-xl font-black text-slate-950">History will appear after verified observations</h2><p className="mt-2 text-sm leading-6 text-slate-600">ShopNdeal does not invent historical prices. Once an authorized merchant or feed observation is available, this product will show its verified price timeline here.</p></section>
  const latest = observations[0]
  const lowest = Math.min(...observations.map((observation) => Number(observation.price)))
  return <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Price intelligence</p><h2 className="mt-2 text-xl font-black text-slate-950">Verified price observations</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">{observations.length} observations</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Observed now</p><p className="mt-1 text-2xl font-black text-slate-950">{formatINR(Number(latest.price))}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">Lowest observed</p><p className="mt-1 text-2xl font-black text-slate-950">{formatINR(lowest)}</p></div></div><div className="mt-5 space-y-2">{observations.slice(0, 5).map((observation) => <div key={observation.observed_at} className="flex items-center justify-between border-t border-slate-100 py-3 text-sm"><span className="text-slate-500">{new Date(observation.observed_at).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</span><span className="font-black text-slate-900">{formatINR(Number(observation.price))}</span><span className="text-xs font-bold capitalize text-slate-400">{observation.availability.replaceAll("_", " ")}</span></div>)}</div><p className="mt-4 text-[11px] leading-5 text-slate-400">Source: authorized observation records. Price and availability can change at the merchant.</p></section>
}
