"use client"

import Link from "next/link"
import { ArrowRight, Check, ExternalLink, Link2, Search, ShieldCheck, Sparkles, Tag, TrendingDown } from "lucide-react"
import { useState } from "react"
import { calculateSavings, categories, formatINR, shopItems } from "@/lib/shop-data"

export function ShopNdealHome() {
  const [query, setQuery] = useState("")
  const [shoppingLink, setShoppingLink] = useState("")
  const [analyzed, setAnalyzed] = useState(false)
  const featured = shopItems.slice(0, 3)
  const savings = calculateSavings(4999)

  return (
    <main className="min-h-screen bg-[#f7f9fc] text-slate-950">
      <section className="overflow-hidden border-b border-slate-200 bg-slate-950 text-white">
        <div className="mx-auto max-w-7xl px-5 py-5"><Link href="/" className="text-sm font-bold tracking-tight text-white/80 hover:text-white">BuyNswipe<span className="text-cyan-300">®</span> <span className="mx-2 text-white/30">/</span> ShopNdeal</Link></div>
        <div className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-24">
          <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/25 bg-cyan-300/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-cyan-200"><Sparkles className="size-3.5" /> Shopping & Savings Intelligence</p><h1 className="max-w-3xl text-5xl font-black tracking-[-.055em] sm:text-6xl">Find the best way to <span className="text-cyan-300">buy & save.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Compare products, deals, coupons, cashback and eligible BuyNswipe benefits before you buy.</p>
            <div className="mt-9 flex max-w-2xl flex-col gap-3 rounded-2xl bg-white p-2 shadow-2xl sm:flex-row"><div className="flex min-w-0 flex-1 items-center gap-3 px-3"><Search className="size-5 shrink-0 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search phones, laptops, fashion..." className="min-w-0 flex-1 bg-transparent py-3 text-sm text-slate-900 outline-none" aria-label="Search products" /></div><Link href={query ? `/shop/products?q=${encodeURIComponent(query)}` : "/shop/products"} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Search <ArrowRight className="size-4" /></Link></div>
            <div className="mt-4 flex flex-wrap gap-2"><Link href="/shop/ai" className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-3 py-1.5 text-xs font-black text-slate-950 hover:bg-cyan-200"><Sparkles className="size-3.5" /> Ask ShopNdeal AI</Link><Link href="/shop/coupons" className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:bg-white/10">Browse coupons</Link><Link href="/shop/deals" className="rounded-full border border-white/15 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:bg-white/10">See today&apos;s deals</Link></div>
          </div>
          <div className="rounded-3xl border border-white/10 bg-white/[.07] p-5 shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-200">Find my savings</p><h2 className="mt-2 text-2xl font-black">Paste a shopping link</h2></div><Link2 className="size-7 text-cyan-300" /></div><textarea value={shoppingLink} onChange={(e) => setShoppingLink(e.target.value)} placeholder="https://merchant.com/product/..." className="mt-6 min-h-24 w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 text-sm text-white outline-none placeholder:text-slate-500 focus:border-cyan-300/60" /><button type="button" onClick={() => setAnalyzed(true)} className="mt-3 w-full rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950 hover:bg-cyan-200">Find My Savings</button>{analyzed ? <div className="mt-4 rounded-2xl bg-emerald-400/10 p-4 text-sm text-emerald-200"><p className="font-bold">Savings routes found for this demo analysis.</p><p className="mt-1 text-emerald-100/70">Connect a merchant link to verify live eligibility.</p></div> : <p className="mt-4 text-xs leading-5 text-slate-400">Potential savings are estimates until eligibility and merchant terms are verified.</p>}</div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-5 py-14"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-blue-600">Explore ShopNdeal</p><h2 className="mt-1 text-3xl font-black tracking-tight">Shop with a smarter starting point.</h2></div><Link href="/shop/products" className="hidden items-center gap-2 text-sm font-bold text-blue-600 sm:flex">View all products <ArrowRight className="size-4" /></Link></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{categories.map((category) => <Link key={category} href={`/shop/products?category=${category}`} className="rounded-2xl border border-slate-200 bg-white px-4 py-5 text-sm font-bold shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md">{category}<ArrowRight className="mt-5 size-4 text-slate-400" /></Link>)}</div></section>
      <section className="bg-white py-14"><div className="mx-auto max-w-7xl px-5"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-blue-600">Verified starting points</p><h2 className="mt-1 text-3xl font-black tracking-tight">Popular ways to save.</h2></div><Link href="/shop/deals" className="hidden text-sm font-bold text-blue-600 sm:block">View deals <ArrowRight className="ml-1 inline size-4" /></Link></div><div className="mt-8 grid gap-5 md:grid-cols-3">{featured.map((item) => <Link key={item.slug} href={`/shop/product/${item.slug}`} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`flex h-36 items-end bg-gradient-to-br ${item.accent} p-5`}><span className="rounded-full bg-white/90 px-2.5 py-1 text-xs font-black text-slate-800">{item.discount}% OFF</span></div><div className="p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-400">{item.merchant}</p>{item.verified && <ShieldCheck className="size-4 text-emerald-500" aria-label="Verified offer" />}</div><h3 className="mt-2 font-black group-hover:text-blue-600">{item.name}</h3><div className="mt-4 flex items-end justify-between"><div><p className="text-xl font-black">{formatINR(item.price)}</p><p className="text-xs text-slate-400 line-through">{formatINR(item.mrp)}</p></div><span className="text-xs font-bold text-emerald-600">+{formatINR(item.cashback)} cashback</span></div></div></Link>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-14"><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold text-blue-600">Savings, explained</p><h2 className="mt-2 text-3xl font-black tracking-tight">See the real route behind the price.</h2><p className="mt-4 max-w-lg leading-7 text-slate-600">We separate verified, eligible and potential savings so the number you see is useful—not overpromised.</p><Link href="/shop/product/noise-cancelling-headphones" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white hover:bg-blue-700">View savings breakdown <ArrowRight className="size-4" /></Link></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Estimated effective price</p><p className="mt-1 text-3xl font-black">{formatINR(savings.effective)}</p></div><TrendingDown className="size-7 text-emerald-500" /></div><div className="space-y-4 pt-5 text-sm"><div className="flex justify-between"><span className="text-slate-500">Product price</span><b>{formatINR(4999)}</b></div><div className="flex justify-between text-emerald-700"><span className="flex items-center gap-2"><Tag className="size-4" /> Verified coupon</span><b>-{formatINR(savings.coupon)}</b></div><div className="flex justify-between text-emerald-700"><span>Potential cashback</span><b>-{formatINR(savings.cashback)}</b></div><div className="mt-2 flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><Check className="size-4" /> Cashback remains potential until the merchant confirms the transaction.</div></div></div></div></section>
      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>ShopNdeal is a BuyNswipe<span className="text-blue-600">®</span> shopping vertical.</p><div className="flex gap-4"><Link href="/shop/wishlist" className="hover:text-blue-600">My watchlist</Link><Link href="/shop/alerts" className="hover:text-blue-600">Price alerts</Link><Link href="/shop/analyze" className="hover:text-blue-600">Analyze a deal</Link><Link href="/shop/price-intelligence" className="hover:text-blue-600">Price intelligence</Link><Link href="/credit" className="hover:text-blue-600">Explore Credit</Link><Link href="/buynswipe-go" className="hover:text-blue-600">Explore BuyNswipe Go</Link></div></div></footer>
    </main>
  )
}
