import Link from "next/link"
import { notFound } from "next/navigation"
import { createClient } from "@/lib/supabase/server"
import { CreditReviewForm } from "../credit-review-form"

export default async function CreditProductPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound()
  const supabase = await createClient()
  const [{ data: product }, { data: sources }, { data: reviews }] = await Promise.all([
    supabase.from("credit_products").select("id, name, provider, product_type, status, rate_text, fee_text, eligibility, source_url, review_due_at, updated_at").eq("id", id).maybeSingle(),
    supabase.from("credit_claim_sources").select("id, claim_type, claim_text, source_url, verified_at, expires_at").eq("product_id", id).order("created_at", { ascending: false }),
    supabase.from("credit_reviews").select("id, decision, notes, created_at").eq("product_id", id).order("created_at", { ascending: false }),
  ])
  if (!product) notFound()
  return <main className="min-h-screen bg-slate-950 text-slate-950"><div className="mx-auto min-h-screen max-w-5xl bg-slate-50 p-6 lg:p-10"><Link href="/admin/credit" className="text-sm font-bold text-slate-500 hover:text-sky-600">← Credit catalog</Link><header className="mt-8"><p className="text-sm font-semibold text-emerald-600">Product governance</p><h1 className="mt-2 text-3xl font-black">{product.name}</h1><p className="mt-2 text-slate-500">{product.provider} · {product.product_type}</p></header><div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-black">Product facts</h2><dl className="grid gap-4 sm:grid-cols-2">{[["Status", product.status], ["Rate / APR", product.rate_text], ["Fees", product.fee_text], ["Review due", product.review_due_at ? new Date(product.review_due_at).toLocaleDateString() : "Not set"]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value || "Not provided"}</dd></div>)}</dl><div><h3 className="text-sm font-black">Eligibility</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{product.eligibility || "No eligibility notes provided."}</p></div><div><h3 className="text-sm font-black">Evidence sources</h3>{sources?.length ? <ul className="mt-3 space-y-3">{sources.map((source) => <li key={source.id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">{source.claim_type}: {source.claim_text}</p><a href={source.source_url} target="_blank" rel="noreferrer" className="mt-1 block truncate text-sky-700 underline">{source.source_url}</a><p className="mt-1 text-xs text-slate-500">Expires {source.expires_at ? new Date(source.expires_at).toLocaleDateString() : "not set"}</p></li>)}</ul> : <p className="mt-2 text-sm text-amber-700">No structured evidence claims have been added.</p>}</div></section><aside className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-black">Reviewer decision</h2><CreditReviewForm productId={product.id} />{reviews?.length ? <div className="mt-6 space-y-3">{reviews.map((review) => <div key={review.id} className="border-t border-slate-100 pt-3"><div className="flex justify-between gap-3 text-sm font-bold"><span className="capitalize">{review.decision.replace("_", " ")}</span><time className="text-xs font-normal text-slate-400">{new Date(review.created_at).toLocaleDateString()}</time></div>{review.notes && <p className="mt-1 text-sm text-slate-600">{review.notes}</p>}</div>)}</div> : null}</aside></div></div></main>
}
