import Link from "next/link"
import { ArrowLeft, CheckCircle2, ExternalLink, Link2, RefreshCw, ShieldCheck, XCircle } from "lucide-react"

const offers = [
  ["Axis Bank ACE Credit Card", "Axis Bank", "Verified", "2026-09-10"],
  ["HDFC Personal Loan", "HDFC Bank", "Redirected", "2026-09-09"],
  ["ICICI Business Loan", "ICICI Bank", "Failed", "2026-09-08"],
]

export default function AdminAffiliatesPage() { return <main className="min-h-screen bg-slate-950 text-slate-950"><div className="mx-auto min-h-screen max-w-7xl bg-slate-50 p-6 lg:p-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-sky-600"><ArrowLeft className="size-4" /> Admin overview</Link><header className="mt-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-violet-600">Partner operations</p><h1 className="mt-2 text-3xl font-black">Affiliate operations</h1><p className="mt-2 text-sm text-slate-500">Monitor offers, destinations, disclosures, and link health.</p></div><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Add offer</button></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Active offers" value="24" /><Metric label="Healthy links" value="21" /><Metric label="Needs attention" value="3" /></div><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col justify-between gap-3 border-b border-slate-200 p-5 sm:flex-row sm:items-center"><div><h2 className="font-black">Offer link health</h2><p className="mt-1 text-sm text-slate-500">Last checks, redirect state, and disclosure readiness.</p></div><button className="inline-flex w-fit items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600"><RefreshCw className="size-3.5" /> Recheck failed</button></div>{offers.map(([name, partner, status, checked]) => <div key={name} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 grid size-9 place-items-center rounded-lg bg-violet-100 text-violet-700"><Link2 className="size-4" /></div><div><p className="font-bold">{name}</p><p className="mt-1 text-sm text-slate-500">{partner} · checked {checked}</p></div></div><div className="flex items-center gap-3"><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${status === "Verified" ? "bg-emerald-100 text-emerald-700" : status === "Redirected" ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700"}`}>{status === "Verified" ? <CheckCircle2 className="size-3.5" /> : status === "Redirected" ? <ExternalLink className="size-3.5" /> : <XCircle className="size-3.5" />} {status}</span><ShieldCheck className="size-4 text-emerald-600" aria-label="Disclosure present" /></div></div>)}</section></div></main> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div> }
