import Link from "next/link"
import { ArrowLeft, CheckCircle2, Link2, RefreshCw, XCircle } from "lucide-react"
import { createClient } from "@/lib/supabase/server"
import { NewOfferForm } from "./new-offer-form"

export default async function AdminAffiliatesPage() {
  const supabase = await createClient()
  const { data } = await supabase.from("affiliate_offers").select("id,name,partner,category,status,health_status,destination_url,disclosure,last_checked_at,updated_at").order("updated_at", { ascending: false })
  const offers = data ?? []
  const active = offers.filter((offer) => offer.status === "active").length
  const healthy = offers.filter((offer) => offer.health_status === "healthy").length
  return <main className="min-h-screen bg-slate-950 text-slate-950"><div className="mx-auto min-h-screen max-w-7xl bg-slate-50 p-6 lg:p-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-sky-600"><ArrowLeft className="size-4" /> Admin overview</Link><header className="mt-8"><p className="text-sm font-semibold text-violet-600">Partner operations</p><h1 className="mt-2 text-3xl font-black">Affiliate operations</h1><p className="mt-2 text-sm text-slate-500">Monitor offers, destinations, disclosures, and link health.</p></header><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Active offers" value={String(active)} /><Metric label="Healthy links" value={String(healthy)} /><Metric label="Total offers" value={String(offers.length)} /></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Add affiliate offer</h2><p className="mb-4 mt-1 text-sm text-slate-500">Every offer requires a destination and visible disclosure.</p><NewOfferForm /></section><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 className="font-black">Offer inventory</h2><p className="mt-1 text-sm text-slate-500">Track link health and disclosure readiness.</p></div><button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600"><RefreshCw className="size-3.5" /> Recheck</button></div>{offers.length ? offers.map((offer) => <div key={offer.id} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 grid size-9 place-items-center rounded-lg bg-violet-100 text-violet-700"><Link2 className="size-4" /></div><div><Link href={`/admin/affiliates/${offer.id}`} className="font-bold hover:text-violet-700">{offer.name}</Link><p className="mt-1 text-sm text-slate-500">{offer.partner} · {offer.category} · {offer.disclosure ? "Disclosure ready" : "Disclosure missing"}</p></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize text-slate-600">{offer.health_status === "healthy" ? <CheckCircle2 className="size-3.5 text-emerald-600" /> : offer.health_status === "failed" ? <XCircle className="size-3.5 text-rose-600" /> : <RefreshCw className="size-3.5" />}{offer.health_status}</span></div>) : <p className="p-8 text-sm text-slate-500">No affiliate offers yet.</p>}</section></div></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div> }
